gitGraph
  commit id: "initial release with details"
  branch "unicode work"
  commit id: "解析 🚀" tag: "candidate" type: HIGHLIGHT
  switch main
  merge "unicode work" id: "integrated release" type: REVERSE
